name: ALBEbank
description: "A simple plugin to manage money in the most realistic way possible"
main: me.albedim.bank.Main
version: 1.0.0
author: albedim
api-version: 1.18
commands:
  card:
    description: none
  transfer:
     description: none
  confirmTransfer:
    description: none
  rejectTransfer:
    description: none
  bank:
    description: none